// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCoreDBContex;

namespace NetCoreDBContex.Migrations
{
    [DbContext(typeof(BlogDBContext))]
    partial class BlogDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NetCoreDBContex.Models.Character", b =>
                {
                    b.Property<int>("Cid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CName")
                        .HasColumnType("text");

                    b.HasKey("Cid");

                    b.ToTable("Character");
                });

            modelBuilder.Entity("NetCoreDBContex.Models.CharacterInMenu", b =>
                {
                    b.Property<int>("CMid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cid")
                        .HasColumnType("int");

                    b.Property<int>("Mid")
                        .HasColumnType("int");

                    b.HasKey("CMid");

                    b.ToTable("CharacterInMenu");
                });

            modelBuilder.Entity("NetCoreDBContex.Models.UserInCharacter", b =>
                {
                    b.Property<int>("UCid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cid")
                        .HasColumnType("int");

                    b.Property<int>("Uid")
                        .HasColumnType("int");

                    b.HasKey("UCid");

                    b.ToTable("UserInCharacter");
                });

            modelBuilder.Entity("NetCoreDBContex.Models.UserInfo", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("NickName")
                        .HasColumnType("text");

                    b.Property<string>("UName")
                        .HasColumnType("text");

                    b.Property<string>("UPwd")
                        .HasColumnType("text");

                    b.HasKey("Uid");

                    b.ToTable("UserInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
